### ISSUE TITLE
conda installs old version

### ISSUE THREAD

**Issue by jayfmil** [pennmem/cmlreaders#148]
"conda install -c pennmem cmlreaders" is installing version 0.2 using python 3.6. This happened to me with both mac and linux.

**Comment by mivade** [comment]
Can you do `conda list`? There's probably something else in your environment that is holding things back. You can also try `conda install -c pennmem cmlreaders=0.8` to see if that will give you hints about version conflicts.

**Comment by jayfmil** [comment]
Thanks. Figured it out. I was using the globally installed version of conda on rhino, which is old and doesn't handle channels the same way as newer versions, and thus wasn't installing the newer version of pandas. I installed a local miniconda, and then everything was fine.

**Comment by mivade** [comment]
I think others have found issues using the global anaconda install, but usually if you start with a fresh environment it works. I'll update the README to make this more clear.
