### ISSUE TITLE
Loading TH events

### ISSUE THREAD

**Issue by jayfmil** [pennmem/cmlreaders#159]
How do you feel about allowing the the user to input the preferred `data_type` to the load method of `CMLReader` when trying to load events? I'm asking because the TH task doesn't have an `all_events` type.

Or if you don't think that is a good idea, could we add another conditional that makes the data_type equal to `task_events` if it is a TH task?

**Comment by mivade** [comment]
Yeah, we should be selecting `task_events` in that case.
