### ISSUE TITLE
Improve how CMLReaders decides which timestamped host PC directory to use

### ISSUE THREAD

**Issue by leondavis1** [pennmem/cmlreaders#164]
* CML Data Readers version: 0.8
* Python version: 3.6

Right now, whenever CMLReaders looks up a file from Ramulator, it uses the directory with the earliest timestamp (i.e. between `host_pc/20180712_134957` and `host_pc/20180712_135217`, it will always return the former). The bulk of the session occurs in the later directory often enough that we should figure out a better way to access these files.

(Yes, this is another problem we get from allowing sessions to be interrupted)

**Comment by mivade** [comment]
Unless I am mistaken, this was fixed in #152.

**Comment by leondavis1** [comment]
I guess what I'm saying is that "use the first timestamped directory" is a decent heuristic but naturally it isn't always correct, and when it isn't correct there should be a way to account for that

**Comment by mivade** [comment]
I have it so that it returns the most recent and gives a warning about finding more than one:

https://github.com/pennmem/cmlreaders/blob/091d4a34c4806053f24c4ac3056943e3b49434aa/cmlreaders/path_finder.py#L188-L193
