### ISSUE TITLE
contacts/pairs scheme input

### ISSUE THREAD

**Issue by jayfmil** [pennmem/cmlreaders#165]
I'm still getting a bit of a handle how to use cmlreaders to load eeg vs using PTSA, and I have some questions about the `scheme` input. 

 I see that if you enter a set of pairs, the code will automatically rereference the data, and the `channels` parameter will be defined by the pairs `label` column. However, is there a way to simply load a specific non-bipolar channel? In the PTSA eeg functions, as well as the old matlab eeg_toolbox, you could enter an arbitrary channel number and load that data. 

Also, if you don't enter a scheme, the `channels` parameter is just a list of incremented channel numbers, instead of the label from the json file. I guess another way of summarizing what I'm asking is, given that you can load pairs.json and pass those as a scheme to `load_eeg`, could we similarly load contacts.json, filter it to any subset, and pass those in as a scheme?

**Comment by esolomon** [comment]
@jayfmil It is my understanding that what you describe in the last paragraph is exactly how CMLReaders is supposed to work! But having tried it myself, I see it does not.

**Comment by mivade** [comment]
Currently `scheme` is for loading bipolar channels only. It shouldn't be too hard for me to update it to also accept `contacts` data to return monopolar channels when possible.
