### ISSUE TITLE
Error attempting to load pyFR eeg

### ISSUE THREAD

**Issue by jayfmil** [pennmem/cmlreaders#179]
I can load pyFR events, but I receive an error when attempting to load eeg:

```
reader = CMLReader("TJ039", experiment="pyFR", session=0)
events = reader.load("events")
word = events[events.type=='WORD']
eeg = reader.load_eeg(events=word, rel_start=-100, rel_stop=100)

...
KeyError: 'experiment'
```
Adding an `experiment` column to the DF then yields a `FileNotFoundError`.

**Comment by mivade** [comment]
It looks like I never actually implemented the EEG loading for pyFR. The main complication is reading the sample rate from the various `*params.txt` files. How likely is that to change from session to session for a given subject?

**Comment by jayfmil** [comment]
Unusual but not impossible. A complete guess, but I'd say >95% of the time they are the same. If you are trying to load multiple sessions and the sample rates do differ, I think raising some sort of error is reasonable, instead of trying to figure out a fancy workaround.

**Comment by mivade** [comment]
Then I think for now I'll handle the case where the one `params.txt` file can be used and figure out how best to handle outliers later. I'll open a separate issue so we can track that.
