### ISSUE TITLE
error reading some sources.json files

### ISSUE THREAD

**Issue by jayfmil** [pennmem/cmlreaders#184]
I'm running into errors when some sources.json files are being processed. The error is:

`TypeError: unhashable type: 'dict'`

Here's an example, using code from `_read_sources_json`.

```
file_path = '/protocols/r1/subjects/R1270J/experiments/TH1/sessions/0/ephys/current_processed/sources.json'
df = pd.read_json(file_path, orient='index')
sources_info = {}

for k in df:
    v = df[k].unique()
    sources_info[k] = v[0] if len(v) == 1 else v
```

The contents of that json file are formatted a little differently than others, I think. I'm finding about 8 TH subjects who have this issue. Not sure about other datasets.

```
{
  "R1270J_TH1_0_13Feb17_0058": {
    "0": {
      "data_format": "int16", 
      "n_samples": 2663545, 
      "sample_rate": 1000, 
      "source_file": "170212-1658/np1-001.ns2", 
      "start_time_ms": 1486947511412, 
      "start_time_str": "13Feb17_0058"
    }, 
    "1": {
      "data_format": "int16", 
      "n_samples": 2662535, 
      "sample_rate": 1000, 
      "source_file": "170212-1658/np2-001.ns2", 
      "start_time_ms": 1486947512417, 
      "start_time_str": "13Feb17_0058"
    }, 
    "data_format": "int16", 
    "n_samples": 2662535, 
    "sample_rate": 1000, 
    "source_file": "np1-001.ns2", 
    "start_time_ms": 1486947511412, 
    "start_time_str": "13Feb17_0058"
  }
```

**Comment by seqasim** [comment]
Jumping on, I have had this same issue with:
R1191J
R1207J 
R1230J
R1236J
R1241J
R1263C
R1267J
R1270J

Is it a coincidence that almost all of these were recorded at a particular hospital site?

**Comment by jayfmil** [comment]
R1191J
R1207J
R1230J
R1236J
R1241J
R1263C
R1267J
R1270J

**Comment by jayfmil** [comment]
Ah you beat me by a few seconds. At least our lists are the same.

**Comment by mivade** [comment]
TH has long been problematic because it never conformed to existing data standards. It looks like there's a problem with event creation that makes the `sources.json` files not follow the same convention as the others. Looping in @leondavis1.

**Comment by leondavis1** [comment]
Strictly speaking it's not because they're TH, but because they were recorded in this multi-NSx format and this is the format that Isaac chose for that file type.

But also, now that I look at it I'm not sure the logic for splitting this file type is correct

**Comment by mivade** [comment]
How can we detect this format? What I don't want is for the general logic of parsing the `sources.json` file to become overly complex, but if we can divert to a separate function that parses differently when it's in that format it's workable. The best solution though is as always to standardize our data storage as much as possible.
