### ISSUE TITLE
EEG loading negative offsets

### ISSUE THREAD

**Issue by esolomon** [pennmem/cmlreaders#201]
* CML Data Readers version: 0.9.2
* Python version: 3.6
* Operating System: 

The load_eeg method seems to not correctly read negative offsets for rel_stop, i.e. you cannot ask for an EEG clip from -1000 ms to -500 ms relative to an event.  Here's an example:

```
eeg = reader.load_eeg(events=evs.iloc()[evidx:evidx+1], rel_start=-100, rel_stop=-50)
eeg.shape

(1, 100, 879172)
```

Looks like it might be doing something like looping around and ultimately loading the entire session's worth of EEG? Either way, this is a critical (but probably easy) fix.

**Comment by mivade** [comment]
I believe @leondavis1 started working on this yesterday.
