### ISSUE TITLE
ValueError: split EEG filenames don't seem to match what are in the events

### ISSUE THREAD

**Issue by LoganJF** [pennmem/cmlreaders#222]
* CML Data Readers version: Current
* Python version: 3.6
* Operating System: Linux

### Description
When attempting to load eeg for ltpFR2, or for some sessions of RAM data, cmlreaders throws a ValueError. 

### What I Did

dataframe_ltp = get_data_index("ltp")
ltp_subjects = dataframe_ltp[dataframe_ltp['experiment']=='ltpFR2']['subject'].unique()

subject = 'LTP093'
session = 1
experiment = 'ltpFR2'

ltp_reader = CMLReader(subject=subject, experiment = experiment, session=session)
ltp_events = ltp_reader.load('events')
encoding = ltp_events[ltp_events['type']=='WORD']
eeg = ltp_reader.load_eeg(events=encoding, rel_start=0, rel_stop=1.6)

# ----------> 
reader = CMLReader(subject='R1207J', experiment='catFR1', session=0)
evs = reader.load('events')
reader.load_eeg(events=evs[evs['type']=='WORD'], rel_start=0., rel_stop=1.)

See also:
https://gist.github.com/LoganJF/4fa6e59a1c19ff80f9195a102d8622c3#file-cml-reader-issues-ipynb

**Comment by leondavis1** [comment]
Closed in https://github.com/pennmem/cmlreaders/releases/tag/v0.9.4
