### ISSUE TITLE
Update package and requirements

### ISSUE THREAD

**Issue by jeremymanning** [pennmem/cmlreaders#225]
* CML Data Readers version: (direct from git)
* Python version: 3.6.2
* Operating System: CentOS(?) (running on rhino in a Conda python 3 environment as per readme instructions)

### Description

I tried to read in data using instructions sent by @leondavis1:
```
An entire EEG recording, using bipolar referencing:

            reader  = cmlreaders.CMLReader(subject=subject,experiment=experiment, session=session)
            pairs = reader.load('pairs')
            _ = reader.load_eeg(scheme=pairs)

To load sections of EEG relative to word onset:

            reader  = cmlreaders.CMLReader(subject=subject,experiment=experiment, session=session)
            events = reader.load('events')
            events = events.loc[events.type=='WORD']
            pairs = reader.load('pairs')
            _ = reader.load_eeg(events=events,rel_start=0,rel_stop=1366,scheme=pairs)

Here the "rel_start" and "rel_stop" arguments are in milliseconds.
```

### What I Did

I installed CMLreaders using the readme instructions, and then tried to read some data using the above instructions

```
In [9]: import cmlreaders

In [10]: reader = cmlreaders.CMLReader(subject='R1016M', experiment='catFR1', session=0)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-139e3a181c8e> in <module>
----> 1 reader = cmlreaders.CMLReader(subject='R1016M', experiment='catFR1', session=0)

AttributeError: module 'cmlreaders' has no attribute 'CMLReader'
```

### Workaround

1. Install h5py using pip (should add to requirements.txt)
2. Install cmlreaders directly from github (`pip install --upgrade git+https://github.com/pennmem/cmlreaders.git`)

Proposed fix: I suggest that you update the package on conda, after updating requirements.txt

**Comment by leondavis1** [comment]
I'm sorry -- is the problem that when installing according to the README you get this error, forcing you to install through Git? Or is there some other errror such that you can't install using `conda`, and then once you install through Git you get this error?

**Comment by jeremymanning** [comment]
It's a problem when I install according to the README instructions.  Installing through Git was the workaround.  All of this was done inside of a Python 3 conda virtual environment.

**Comment by leondavis1** [comment]
2 followup questions:

1. What version of `conda` are you using?
2. When you install `cmlreaders` using `conda`, which version of `cmlreaders` gets installed?

**Comment by jeremymanning** [comment]
1. whatever version of conda is the default on rhino
2. not sure...but you could easily test by following the readme instructions in a new virtual environment, right?

**Comment by leondavis1** [comment]
So the issue seems to be that the default `conda` on Rhino is version 3.9, and for some reason that version isn't able to locate versions of cmlreaders past v0.1.1.

For reference, the current version is 0.9.4.

I'll talk to IT about upgrading the default `conda` installation
