### ISSUE TITLE
catFR1 load_events broken

### ISSUE THREAD

**Issue by dhalpern** [pennmem/cmlreaders#239]
* CML Data Readers version: 0.9.8
* Python version: 3.7.9
* Operating System: linux? (rhino)

### Description

load_events crashes with catFR1 because one subject does not have an all_events.json in the right place.

### What I Did

```
import cmlreaders as cml
reader.load_events(experiments="catFR1")
```

This returns
```
FileNotFoundError: Unable to find the requested file in any of the expected locations:
 /protocols/r1/subjects/R1221P/experiments/catFR1/sessions/0/behavioral/current_processed/all_events.json
/data/events/pyFR/R1221P_events.mat
```

This subject indeed appears not to have an all_events.json although they do have a task_events.json. Perhaps it would be useful to add functionality to load_events to only return task_events? Alternately, perhaps it should just skip over missing subjects or throw a warning but still return a data frame. Alternately^2, we should track down this file!

Happy to try to work on these, just not sure what the best option would be.

**Comment by dhalpern** [comment]
I should note that the following works so it appears to be only this subject:

```
ix = cml.get_data_index()
catfr1_subjects = ix.query('experiment == "catFR1" and subject != "R1221P"').subject.unique()
all_catfr1_events = cml.CMLReader.load_events(subjects=catfr1_subjects, experiments="catFR1")
```

**Comment by jrudoler** [comment]
I basically never use this method of loading events so I have yet to come across this problem, thanks for raising it. I think it would be good to make the type of events file loaded configurable (i.e. task_events, all_events, math_events), and also print a warning that globs the available files for that subject/session if they don't have the requested one.

**Comment by dhalpern** [comment]
This is still an
