### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mivade** [pennmem/cmlreaders#38]
I think it's about time for a new release (mainly for a new conda package for easier feedback from users). Things to do first:

- [x] Update README by removing the proposal and showing examples of what is actually implemented now
- [x] Ensure documentation is up to date and rebuild
- [x] Do some QA testing on the EEG reading (e.g., make sure that when loading by events we get the right clips)

Since we've added quite a bit of functionality, should we call this version 0.4?

**Comment by zduey** [comment]
This makes sense to me. The two things I can take care of are to update the getting started guide and then I also want to add the high-level data dictionary to the documentation for this round. Basically, I'll take that middle item and can help with the others if they are still not done by the time I finish. Let's shoot for tomorrow as a release?

**Comment by zduey** [comment]
Closing because of 0.4.0 release.
