### ISSUE TITLE
Add support for filtering by contacts

### ISSUE THREAD

**Issue by zduey** [pennmem/cmlreaders#50]
Right now, the EEG reader allows you to filter based on events, but another common use case is to only load eeg corresponding to particular channels. @mivade's proposed API was:

```python
# get electrode contact info as a DataFrame
# this will have contact labels, locations, regions, coordinates, etc.
contacts = reader.load('contacts')

# or specify only contacts that are located in the MTL
# require_monopolar will raise an exception if monopolar is not possible
subset_eeg = reader.load('eeg',
                         contacts=contacts[contacts.region == 'MTL'],
                         require_monopolar=True)
```

**Comment by mivade** [comment]
The existing API looks like this:

```python
def load_eeg(self, events: Optional[pd.DataFrame] = None,
             rel_start: int = None, rel_stop: int = None,
             epochs: Optional[List[Tuple[int, int]]] = None,
             contacts: Optional[pd.DataFrame] = None,
             scheme: Optional[pd.DataFrame] = None):
```

`scheme` is the referencing scheme to (try) to rereference with (an exception is raised when this is not possible).

`contacts` is accepted right now, but each EEG reader class currently raises a `NotImplementedError` when passing this until somebody implements it.

**Comment by mivade** [comment]
Accidentally done already, and now made more explicit: just pass `scheme` with the ones you care about.
