### ISSUE TITLE
Multi-session event reading

### ISSUE THREAD

**Issue by zduey** [pennmem/cmlreaders#53]
A common use case when working with events is to load multiple sessions at a time. Right now, this is not as easy as it should be.

```python
all_events = []
for session in sessions_completed:
    sess_events = cml.CMLReader(subject="R1409D", experiment="FR6", session=session,
                                localization=0, montage=0, rootdir=rhino_root).load('task_events')
    all_events.append(sess_events)
all_sessions_df = pd.concat(all_events)
```

The proposed API is to have a special method associated with cml_reader to allow loading multiple sessions of events. The other option is to allow additional kwargs in .load(), but then it becomes extremely difficult to document that function since it would take different parameters depending on the data type being loaded. Instead, we want to mimic the behavior of load_eeg and have it be a separate method associated with the class.  Single sessions of events can be loaded using either reader.load() after having specified a session when creating the reader, or by using reader.load_events(sessions=[1]).  At a minimum, the following cases should be handled:

- Given a single experiment, load all completed sessions
- Given a single experiment, load a specific subset of sessions

```python
reader = CMLReader(subject="R1409D",  experiment="FR6")

# Load all sessions
all_fr6_events = reader.load_events()

# Load specific sessions
subset_fr5_events = reader.load_events(sessions=[0, 1])

```

- Given multiple experiments, load all completed sessions from each experiment
- Given a reader with no experiment specified, raise an error if load_events is called

```python
reader = CMLReader(subject="R1409D")

# Invalid Request
all_events = reader.load_events()

# Load sessions across experiments
all_record_only_events = reader.load_events(experiments=['catFR1', 'FR1'])
```

Depending on if it is important enough of a use case, it could also handle the following cases:

- Given multiple experiments and a specific session, load that session number of each experiment, i.e. the first session of FR1 and catFR1 for a particular subject
- Given multiple experiments and a specific set of sessions, load those specific sessions for each experiment given, raising an error if any of the requested session/experiment combinations are not available

```python
reader = CMLReader(subject="R1409D")

# Multi-experiment, single session
multi_exp_single_sess = reader.load_events(experiments=['catFR1', 'FR1'], sessions=[0])

# Multi-experiment, multi-session
multi_exp_multi_sess =  reader.load_events(experiments=['catFR1', 'FR1'], sessions=[0, 1])
```

**Comment by mivade** [comment]
Your example of the present "bad" interface is a bit contrived. It's simpler if you use list comprehension:

```python
events = pd.concat([
    CMLReader(subject, experiment, session).load("events")
    for session in sessions
])
```

This of course assumes elsewhere you've defined `subject`, `experiment`, and `sessions`.

**Comment by esolomon** [comment]
What's the status on this feature? Looking in the latest version (and the documentation), it's not clear to me whether multi-session loading has been enabled yet. At the very least, it appears that passing a list of sessions to the reader does not work.

**Comment by mivade** [comment]
It's not clear to me how this can be done due to the variety of readers that exist. I think in most cases, list comprehension does this for you easily enough. However, I'm not opposed to adding some specialized methods for common cases if that makes things easier.
