### ISSUE TITLE
Ensure compatibility with Jupyter

### ISSUE THREAD

**Issue by esolomon** [pennmem/cmlreaders#57]
Unless a user is paying careful attention, Jupyter, CMLReader, pandas, and MNE have dependency conflicts, causing Jupyter kernel errors. Some of these might not be obvious to a developer who is testing functionality in plain Python or iPython. 

Usually, it seems Jupyter issues can be resolved by simply re-installing Jupyter ('conda install jupyter') after they've installed other packages. But this isn't ideal, especially if we're interested in getting first-time users up-and-running with a simple conda install. The current setup virtually guarantees that new lab members will attempt to get a CML/PTSA/Jupyter Anaconda environment working, fail, and come to others looking for help. 

I've found that for Python 3 environments, at the least: 

- Users will need to ensure pandas 0.22 or 0.23 is installed from conda-forge.
- Users will need to re-install Jupyter and pytz after installing PTSA or MNE. 

I suspect these issues will change or get swapped for other problems as any of the above packages are updated.

**Comment by zduey** [comment]
@esolomon -- Perhaps this is not a cmlreaders specific issue, but one thing that could be done to make life easier for new lab members is to maintain a conda environment file for installing all of the common CML libraries:
- PTSA
- MNE
- cmlreaders
- ramutils?
- jupyter

**Comment by esolomon** [comment]
@zduey Yeah, it's probably not CMLReaders-specific, but it's an issue users would encounter when attempting to install and use CMLReaders. But I agree, a (well-curated) conda environment file for lab users would be a good solution.

**Comment by mivade** [comment]
I created such an environment a while back but it seemed like nobody was using it: https://github.com/pennmem/rhino-quickstart

**Comment by esolomon** [comment]
Okay, maybe time to revive that, get it up-to-date, and advertise it more prominently?

**Comment by mivade** [comment]
Probably. Maybe a better way to handle default packages is to have a metapackage that just pulls in the common dependencies. That way users can also easily create a fresh environment with the standard tools.

**Comment by mivade** [comment]
@esolomon are new people currently instructed to make new conda environments? Or is the standard practice to just use the default global environment?

I was thinking about this, and I think if we can convince people that they should make their own environments, we can solve most of these problems with a conda metapackage that gets the standard tools with a command like:

```
$ conda install -n myenv -c pennmem cmltools
```

**Comment by mivade** [comment]
Closing this since it seems like cmlreaders installs just fine.
