### ISSUE TITLE
Loading Split EEG with Missing Channels Fails Silently

### ISSUE THREAD

**Issue by zduey** [pennmem/cmlreaders#59]
For some subjects that have split EEGs, CML readers does not correctly handle non-sequential or missing channels. For example:

```python
reader = CMLReader(subject="R1006P", experiment="FR2", session=1)
eeg = reader.load_eeg()
```
The returned timeseries includes CH0, CH1, CH99, and CH100. None of these channels exist in the noreref directory for this subject/experiment/session combination. It appears that cmlreaders is assuming that all channels exist consecutively. It is not clear why these channels are not in the noreref directory, but the channels that are present are consistent with the channels listed in the jacksheet. At least for this subject, the split channels are also consistent with what is in the pairs.json file for the montage that was used in this session.

**Comment by mivade** [comment]
Relevant lines to change:

https://github.com/pennmem/cmlreaders/blob/d85d7d709ecd21a3130670c484d1b3be10b25650/cmlreaders/readers/eeg.py#L175-L180

This is just getting all files in the directory and assumes that there are no gaps. We'll have to think of a better way to handle this. This may also affect how rereferencing happens.

**Comment by mivade** [comment]
We need to do the following:

- base eeg reader `read` method needs to return array *and* contact numbers
- `SplitEEGReader` needs to read based on filename
- rereferencing needs to be updated to work with gaps in contact numbers
- `TimeSeries.channels` should be `TimeSeries.contacts` and contain a list of contact numbers
