### ISSUE TITLE
Montage/Localization handled incorrectly

### ISSUE THREAD

**Issue by zduey** [pennmem/cmlreaders#61]
cmlreaders incorrectly uses the localization number to look up special subject identifiers instead of the montage number. For example, R1006P had a montage change that was not the result of a re-implant. Therefore, the montage number was incremented, but the localization number was not. Attempting to request pairs information for this subject results in an error:

```python
reader = CMLReader(subject="R1006P", localization=0, montage=1)
pairs_df = reader.load("pairs") # returns a key error
```
Instead, the montage number should always be used when looking up data in /data10/...
When loading data from the /protocols "database", both the localization and montage numbers are needed.

**Comment by mivade** [comment]
This detail should be documented. I wasn't aware that this difference existed between /data and /protocols.
