### ISSUE TITLE
CMLReader.load_eeg() fails on sessions with >1 EEG file per session

### ISSUE THREAD

**Issue by leondavis1** [pennmem/cmlreaders#66]
* CML Data Readers version: 0.4.0
* Python version: 3.6
* Operating System: Mac OS

### Description
R1384J, experiment FR1, session 1 is split into 2 HDF5 files due to a pause in the session; 
CMLReader is unable to load the data for this session. 

### What I Did

``` python
reader = CMLReader(subject='R1384J',experiment='FR1',session=1)
events = reader.load('events')
eeg = reader.load_eeg(events,0,100)

Traceback (most recent call last):
  File "/Users/leond/anaconda2/envs/thetamod/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-cbd19709a38f>", line 1, in <module>
    eeg  = reader.load_eeg(events,0,100)
  File "/Users/leond/anaconda2/envs/thetamod/lib/python3.6/site-packages/cmlreaders/cmlreader.py", line 164, in load_eeg
    return self.load('eeg', **kwargs)
  File "/Users/leond/anaconda2/envs/thetamod/lib/python3.6/site-packages/cmlreaders/cmlreader.py", line 94, in load
    rootdir=self.rootdir).load(**kwargs)
  File "/Users/leond/anaconda2/envs/thetamod/lib/python3.6/site-packages/cmlreaders/readers/eeg.py", line 274, in load
    return self.as_timeseries(**kwargs)
  File "/Users/leond/anaconda2/envs/thetamod/lib/python3.6/site-packages/cmlreaders/readers/eeg.py", line 343, in as_timeseries
    data = reader.read()
  File "/Users/leond/anaconda2/envs/thetamod/lib/python3.6/site-packages/cmlreaders/readers/eeg.py", line 210, in read
    data = np.array([ts[epoch[0]:epoch[1], :].T for epoch in self.epochs])
ValueError: could not broadcast input array from shape (178,100) into shape (178)
```

**Comment by mivade** [comment]
This seems to me more like a bug in the post-processing, I think. I'm really not sure how to properly handle this kind of thing here, and quite honestly, we shouldn't be allowing pauses in sessions in the first place (I know this seems like a losing battle...).

**Comment by leondavis1** [comment]
I would describe it as "an annoying feature of the post-processing" rather than a bug, since (a) I believe this issue can come up in older sessions as well, and (b) pauses exist in the recordings, and we have to handle that.

The way this is handled in PTSA is by matching against the file name in the events structure, or requiring that the user provide the name of a particular recording when not using an events structure.

**Comment by mivade** [comment]
OK, then a bug in the decision to allow resuming a session.

**Comment by leondavis1** [comment]
I would describe it as "an annoying feature of the post-processing" rather than a bug, since (a) I believe this issue can come up in older sessions as well, and (b) pauses exist in the recordings, and we have to handle that.

The way this is handled in PTSA is by matching against the file name in the events structure, or requiring that the user provide the name of a particular recording when not using an events structure.

**Comment by mivade** [comment]
How did the readers in ptsa handle this?

What I don't like about either solution is it makes reading this malformed (in my opinion) data extremely fragile.

**Comment by mivade** [comment]
Proposal:

- Update so that we are tracking numbers of "subsessions" with basenames or whatever
- Update so that epochs are a list of 3-tuples instead of 2-tuples with each being `(subsession_index, start_offset, stop_offset)` and each offset is relative to that particular subsession so that we know which files to look at
- Update `events_to_epochs` to do the above
- If passing epochs explicitly with `CMLReader.load_eeg`, allow 2-tuples and just assume there's only the one subsession (i.e., insert a 0 for each epoch) and let that be the user's problem if that's how they're loading data

**Comment by mivade** [comment]
Closing via #68.
